name: tiled
version: 0.8.0
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    
  archive: ^3.1.2
  xml: ^5.0.2

dev_dependencies:
   test: any


